### PR TITLE
Feature/question list difficulty

### PR DESCRIPTION
**Pull request by TerezaSkutova**
## Summary

🚨 Provide a brief summary of your work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (non-breaking change to code and structure)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Testing

🚨 Provide info about the new tests and tests result

## Notes

🚨 QuestionSetModel is extended by Difficulty value object calculated in usecase.

### CODE REVIEW

**Comment by PlesnikJakub** [comment]
image

**Comment by PlesnikJakub** [comment]
Hey, dont mind my simple joke above, your code looks well structured and there is not much to criticize. 😊 

After lengthy consideration I would change "QuestionSetList" to "QuestionSetListITem" since its not whole list but literally one item. We are picking name on very small number of classes and that causes all this kinds of debates. With time domain will consist of more items and it will make much more sense.

⚠️ Unit tests are failing(compilation issue) probably due to changes in return types.
⚠️ Coverage is lowered probably by the extension of existing methods. Look for uncovered lines, If you don't know how to address them we can work this out together through pair programming session.

I am sorry for pipelines providing false positives, there is an issue for it and I hope it will be fixed soon. :)

**Comment by PlesnikJakub** [comment]
## Failing tests issue
Hey @TerezaSkutova, after investigation I found a couple of interesting facts. 
- errors printed inside the console are from EF logs resulting from intentionally failing tests. (ignore them)
- the pipeline is failing due to one test in particular `Get_ValidRequest_ReturnsAllLists` - less visible in the pipeline log :( 
- you are a little bit out of sync with master - always merge or rebase to stay up to date


The root cause is in `GetQuestionSetsUseCase.cs line 41` - repository returned empty list of questions. causes difficulty to be calculated as null and the code throws an exception.

**Comment by PlesnikJakub** [comment]
Try this test :)
```csharp
    [Fact]
    public async Task Execute_RepositoryReturnsNoQuestions_Ok()
    {
        var questionSetRepositoryMock = new Mock<IQuestionSetRepository>();
        questionSetRepositoryMock.Setup(x => x.GetAll().Result).Returns(QuesionSets);

        var questionRepositoryMock = new Mock<IQuestionRepository>();

        var outputPortMock = new Mock<IOutputPort>();
        outputPortMock.Setup(x => x.Ok(It.IsAny<IEnumerable<QuestionSetListItem>>()))
           .Callback<IEnumerable<QuestionSetListItem>>(result => Assert.Equal(0, result.First().Difficulty.value));

        var input = new GetQuestionSetsInput();
        var useCase = new GetQuestionSetsUseCase(questionSetRepositoryMock.Object, questionRepositoryMock.Object);
        useCase.SetOutputPort(outputPortMock.Object);

        await useCase.Execute(input);

        outputPortMock.Verify(x => x.Ok(It.IsAny<IEnumerable<QuestionSetListItem>>()), Times.Once());
        outputPortMock.Verify(x => x.Invalid(), Times.Never());
        outputPortMock.Verify(x => x.NotFound(), Times.Never());
    }
```

**Review by TomasNiemczyk98 — DISMISSED** [review]
Looks good to me!

**Review by PlesnikJakub — CHANGES_REQUESTED** [review]

**Review by PlesnikJakub — APPROVED** [review]
🚀

**Pull request merged**
