### PR TITLE
Fix route name and adjust test

### PR DESCRIPTION
**Pull request by obinnadtq**
## Summary

FIxed the route name to follow REST standard and adjusted the corresponding test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactoring (non-breaking change to code and structure)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Testing

Adjusted test to reflect new api endpoint

## Notes

🚨 Anything else

### CODE REVIEW

**Review by TomasNiemczyk98 — APPROVED** [review]
LGTM! Also I am not sure why is the 2nd pipeline still being run @PlesnikJakub ?

**Review by PlesnikJakub — APPROVED** [review]

**Comment by PlesnikJakub** [comment]
Hey, @obinnadtq thank you for your contribution and I apologize for the late response. We had holidays in CZ so it took a little bit longer than usual. 😊  Hope I see you around 🚀

**Comment by PlesnikJakub** [comment]
Hey @petrspelos, pipeline is still failing for contribution from forked repos, we need to revisit this issue :(

**Comment by obinnadtq** [comment]
Hey @PlesnikJakub, it is no problem. Hope to contribute more

**Pull request merged**
